/* SkhemaTypesModule.kt
 * Copyright (C) 2025  Zymus
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published
 * by the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */
package games.studiohummingbird.skhema.types.serializable.modules

import kotlinx.serialization.modules.SerializersModule

val SkhemaTypesModule = SerializersModule {
    include(AcceptActionModule)
    include(AccommodationModule)
    include(AchieveActionModule)
    include(ActionModule)
    include(ActivateActionModule)
    include(AgreeActionModule)
    include(AdministrativeAreaModule)
    include(AllocateActionModule)
    include(ApartmentModule)
    include(ApplyActionModule)
    include(ArriveActionModule)
    include(AskActionModule)
    include(AssessActionModule)
    include(AssignActionModule)
    include(AudienceModule)
    include(AuthorizeActionModule)
    include(BefriendActionModule)
    include(BookmarkActionModule)
    include(BorrowActionModule)
    include(BuyActionModule)
    include(CampingPitchModule)
    include(CancelActionModule)
    include(CheckActionModule)
    include(CheckInActionModule)
    include(CheckOutActionModule)
    include(ChooseActionModule)
    include(CityModule)
    include(CommentActionModule)
    include(CommunicateActionModule)
    include(ConfirmActionModule)
    include(ConsumeActionModule)
    include(ControlActionModule)
    include(CookActionModule)
    include(CountryModule)
    include(CreateActionModule)
    include(DeactivateActionModule)
    include(DefinedTermModule)
    include(DepartActionModule)
    include(DisagreeActionModule)
    include(DiscoverActionModule)
    include(DislikeActionModule)
    include(DonateActionModule)
    include(DrawActionModule)
    include(DrinkActionModule)
    include(EatActionModule)
    include(EndorseActionModule)
    include(ExerciseActionModule)
    include(FilmActionModule)
    include(FindActionModule)
    include(FollowActionModule)
    include(HotelRoomModule)
    include(HouseModule)
    include(IgnoreActionModule)
    include(InformActionModule)
    include(InstallActionModule)
    include(IntangibleModule)
    include(InteractActionModule)
    include(InviteActionModule)
    include(JoinActionModule)
    include(LeaveActionModule)
    include(LikeActionModule)
    include(ListenActionModule)
    include(LoseActionModule)
    include(MarryActionModule)
    include(MeetingRoomModule)
    include(MoveActionModule)
    include(MusicGroupModule)
    include(ObservationModule)
    include(OrderActionModule)
    include(OrganizeActionModule)
    include(PaintActionModule)
    include(PatientModule)
    include(PayActionModule)
    include(PerformActionModule)
    include(PersonModule)
    include(PhotographActionModule)
    include(PlaceModule)
    include(PlanActionModule)
    include(PlayActionModule)
    include(PlayGameActionModule)
    include(PostalAddressModule)
    include(PreOrderActionModule)
    include(QuantitativeValueModule)
    include(QuoteActionModule)
    include(ReactActionModule)
    include(ReadActionModule)
    include(RegisterActionModule)
    include(RejectActionModule)
    include(RentActionModule)
    include(ReplyActionModule)
    include(ReserveActionModule)
    include(ResumeActionModule)
    include(ReviewActionModule)
    include(RoomModule)
    include(RsvpActionModule)
    include(ScheduleActionModule)
    include(SchoolDistrictModule)
    include(SearchActionModule)
    include(SeekToActionModule)
    include(SellActionModule)
    include(ShareActionModule)
    include(SingleFamilyResidenceModule)
    include(SolveMathActionModule)
    include(StateModule)
    include(StructuredValueModule)
    include(SubscribeActionModule)
    include(SuiteModule)
    include(SuspendActionModule)
    include(ThingModule)
    include(TieActionModule)
    include(TipActionModule)
    include(TrackActionModule)
    include(TradeActionModule)
    include(TransferActionModule)
    include(TravelActionModule)
    include(UnRegisterActionModule)
    include(UseActionModule)
    include(ViewActionModule)
    include(VoteActionModule)
    include(WantActionModule)
    include(WatchActionModule)
    include(WearActionModule)
    include(WriteActionModule)
    include(WinActionModule)
}
