/* ThingModule.kt
 * Copyright (C) 2025  Zymus
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published
 * by the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */
package games.studiohummingbird.skhema.types.serializable.modules

import games.studiohummingbird.skhema.types.Thing
import games.studiohummingbird.skhema.types.serializable.*
import kotlinx.serialization.modules.SerializersModule
import kotlinx.serialization.modules.polymorphic

val ThingModule = SerializersModule {
    polymorphic(Thing::class) {
        serializableAcceptAction()
        serializableAccommodation()
        serializableAchieveAction()
        serializableActivateAction()
        serializableAction()
        serializableAddAction()
        serializableAdministrativeArea()
        serializableAgreeAction()
        serializableAllocateAction()
        serializableApartment()
        serializableAppendAction()
        serializableApplyAction()
        serializableArriveAction()
        serializableAskAction()
        serializableAssessAction()
        serializableAssignAction()
        serializableAudience()
        serializableAuthorizeAction()
        serializableBefriendAction()
        serializableBookmarkAction()
        serializableBorrowAction()
        serializableBuyAction()
        serializableCampingPitch()
        serializableCancelAction()
        serializableCheckAction()
        serializableCheckInAction()
        serializableCheckOutAction()
        serializableChooseAction()
        serializableCity()
        serializableCommentAction()
        serializableCommunicateAction()
        serializableConfirmAction()
        serializableConsumeAction()
        serializableControlAction()
        serializableCookAction()
        serializableCountry()
        serializableCreateAction()
        serializableDeactivateAction()
        serializableDefinedTerm()
        serializableDeleteAction()
        serializableDepartAction()
        serializableDisagreeAction()
        serializableDiscoverAction()
        serializableDislikeAction()
        serializableDonateAction()
        serializableDownloadAction()
        serializableDrawAction()
        serializableDrinkAction()
        serializableEatAction()
        serializableEndorseAction()
        serializableExerciseAction()
        serializableFilmAction()
        serializableFindAction()
        serializableFollowAction()
        serializableGiveAction()
        serializableHotelRoom()
        serializableHouse()
        serializableIgnoreAction()
        serializableInformAction()
        serializableInsertAction()
        serializableInstallAction()
        serializableIntangible()
        serializableInteractAction()
        serializableInviteAction()
        serializableJoinAction()
        serializableLeaveAction()
        serializableLendAction()
        serializableLikeAction()
        serializableListenAction()
        serializableLoseAction()
        serializableMarryAction()
        serializableMeetingRoom()
        serializableMoneyTransfer()
        serializableMoveAction()
        serializableMusicGroup()
        serializableObservation()
        serializableOrderAction()
        serializableOrganizeAction()
        serializablePaintAction()
        serializablePatient()
        serializablePayAction()
        serializablePerformAction()
        serializablePerson()
        serializablePhotographAction()
        serializablePlace()
        serializablePlanAction()
        serializablePlayAction()
        serializablePlayGameAction()
        serializablePostalAddress()
        serializablePreOrderAction()
        serializablePrependAction()
        serializableQuantitativeValue()
        serializableQuoteAction()
        serializableReactAction()
        serializableReadAction()
        serializableReceiveAction()
        serializableRegisterAction()
        serializableRejectAction()
        serializableRentAction()
        serializableReplaceAction()
        serializableReplyAction()
        serializableReserveAction()
        serializableResumeAction()
        serializableReturnAction()
        serializableReviewAction()
        serializableRoom()
        serializableRsvpAction()
        serializableScheduleAction()
        serializableSchoolDistrict()
        serializableSearchAction()
        serializableSeekToAction()
        serializableSellAction()
        serializableSendAction()
        serializableShareAction()
        serializableSingleFamilyResidence()
        serializableSolveMathAction()
        serializableState()
        serializableStructuredValue()
        serializableSubscribeAction()
        serializableSuite()
        serializableSuspendAction()
        serializableTakeAction()
        serializableTaxon()
        serializableThing()
        serializableTieAction()
        serializableTipAction()
        serializableTrackAction()
        serializableTradeAction()
        serializableTransferAction()
        serializableTravelAction()
        serializableUnRegisterAction()
        serializableUpdateAction()
        serializableUseAction()
        serializableVehicle()
        serializableViewAction()
        serializableVoteAction()
        serializableWantAction()
        serializableWatchAction()
        serializableWearAction()
        serializableWinAction()
        serializableWriteAction()
    }
}
