/* Text.kt
 * Copyright (C) 2025  Zymus
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published
 * by the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */
package games.studiohummingbird.skhema.datatypes

import games.studiohummingbird.skhema.properties.*

interface Text
    : Abstract
    , AcceptedPaymentMethod
    , AcceptsReservations
    , AccessCode
    , AccessMode
    , AccessibilityAPI
    , AccessibilityControl
    , AccessibilityFeature
    , AccessibilityHazard
    , AccessibilitySummary
    , AccommodationCategory
    , AccountId
    , AcrissCode
    , ActionOption
    , ActionPlatform
    , ActiveIngredient
    , ActivityFrequency
    , AdditionalName
    , AdditionalType
    , AdditionalVariable
    , Address
    , AddressCountry
    , AddressLocality
    , AddressRegion
    , AdministrationRoute
    , Aircraft
    , AlcoholWarning
    , Algorithm
    , AlignmentType
    , AlternateName
    , AlternativeHeadline
    , ApplicableCountry
    , ApplicationCategory
    , ApplicationDeadline
    , ApplicationSubCategory
    , ApplicationSuite
    , AreaServed
    , ArrivalGate
    , ArrivalPlatform
    , ArrivalTerminal
    , ArtEdition
    , ArtMedium
    , ArtForm
    , ArticleBody
    , ArticleSection
    , ArtworkSurface
    , Asin
    , Aspect
    , Assembly
    , AssemblyVersion
    , Assesses
    , AssociatedPathophysiology
    , AudienceType
    , AvailableLanguage
    , AvailableOnDevice
    , Award
    , Awards
    , Backstory
    , BankAccountType
    , Bed
    , BeneficiaryBank
    , Benefits
    , BestRating
    , BiomechanicalClass
    , Bitrate
    , BoardingGroup
    , BodyLocation
    , BodyType
    , BookEdition
    , Box
    , BranchCode
    , Breadcrumb
    , BreastfeedingWarning
    , BroadcastChannelId
    , BroadcastDisplayName
    , BroadcastFrequency
    , BroadcastServiceTier
    , BroadcastSignalModulation
    , BroadcastSubChannel
    , BroadcastTimezone
    , BrowserRequirements
    , BusName
    , BusNumber
    , ByDay
    , CallSign
    , Caption
    , CarrierRequirements
    , CatalogNumber
    , Category
    , CertificationIdentification
    , CharacterName
    , CheckoutPageURLTemplate
    , ChemicalComposition
    , ChildTaxon
    , Circle
    , Citation
    , ClaimReviewed
    , ClincalPharmacology
    , ClinicalPharmacology
    , ClipNumber
    , CodeSampleType
    , CodeValue
    , CodingSystem
    , Color
    , CommentText
    , CompetencyRequired
    , ConditionsOfAccess
    , ConfirmationNumber
    , ContactType
    , ContentRating
    , ContentSize
    , ContentType
    , Contraindication
    , CookingMethod
    , CopyrightNotice
    , Correction
    , CostCurrency
    , CostOrigin
    , CostPerUnit
    , CountriesNotSupported
    , CountriesSupported
    , CountryOfAssembly
    , CountryOfLastProcessing
    , CourseCode
    , CourseMode
    , CoursePrerequisites
    , CourseWorkload
    , CreativeWorkStatus
    , CredentialCategory
    , CreditText
    , CurrenciesAccepted
    , Currency
    , CvdCollectionDate
    , CvdFacilityCountry
    , CvdFacilityId
    , DataFeedElement
    , Dateline
    , DefaultValue
    , DepartureGate
    , DeparturePlatform
    , DepartureTerminal
    , Dependencies
    , Description
    , Device
    , DietFeatures
    , DisambiguationDescription
    , Discount
    , DiscountCode
    , DiscountCurrency
    , DosageForm
    , DoseUnit
    , DriveWheelConfiguration
    , DrugUnit
    , Duns
    , EditEIDR
    , EduQuestionType
    , EducationRequirements
    , EducationalCredentialAwarded
    , EducationalFramework
    , EducationalLevel
    , EducationalProgramMode
    , EducationalRole
    , EducationalUse
    , Elevation
    , EligibilityToWorkRequirement
    , EligibleRegion
    , Email
    , EmbeddedTextCaption
    , EmployerOverview
    , EmploymentType
    , EncodingFormat
    , EncodingType
    , EngineType
    , Epidemiology
    , EpisodeNumber
    , EstimatedCost
    , EstimatedFlightDuration
    , EvidenceOrigin
    , ExecutableLibraryName
    , ExerciseType
    , ExifData
    , ExpectedPrognosis
    , ExperienceRequirements
    , ExpertConsiderations
    , ExtendedAddress
    , FamilyName
    , FaxNumber
    , FeatureList
    , FeesAndCommissionsSpecification
    , FileFormat
    , FileSize
    , FinancialAidEligible
    , FlightDistance
    , FlightNumber
    , FloorLevel
    , Followup
    , FoodWarning
    , Frequency
    , FuelType
    , FunctionalClass
    , GameAvailabilityType
    , GameEdition
    , GamePlatform
    , Gender
    , Genre
    , GeoRadius
    , GivenName
    , GlobalLocationNumber
    , Gtin
    , Gtin12
    , Gtin13
    , Gtin14
    , Gtin8
    , HasBioPolymerSequence
    , HasMenu
    , HasRepresentation
    , HasTierRequirement
    , Headline
    , HealthPlanCoinsuranceOption
    , HealthPlanCopayOption
    , HealthPlanDrugOption
    , HealthPlanDrugTier
    , HealthPlanId
    , HealthPlanNetworkId
    , HealthPlanNetworkTier
    , HealthPlanPharmacyCategory
    , HighPrice
    , HonorificPrefix
    , HonorificSuffix
    , HowPerformed
    , HttpMethod
    , IataCode
    , IcaoCode
    , Identifier
    , InChI
    , InChIKey
    , InLanguage
    , InProductGroupWithID
    , InSupportOf
    , IncentiveCompensation
    , Incentives
    , IncomeLimit
    , Industry
    , IneligibleRegion
    , InfectiousAgent
    , Ingredients
    , Intensity
    , InteractivityType
    , Isbn
    , IsicV4
    , Iso6523Code
    , IsrcCode
    , Issn
    , IssueNumber
    , IswcCode
    , ItemListElement
    , ItemListOrder
    , ItemLocation
    , IupacName
    , JobBenefits
    , JobLocationType
    , JobStartDate
    , JobTitle
    , Jurisdiction
    , Keywords
    , KnownVehicleDamages
    , KnowsAbout
    , KnowsLanguage
    , Latitude
    , LearningResourceType
    , LegalName
    , LegalStatus
    , LegislationIdentifier
    , LegislationJurisdiction
    , LegislationType
    , LeiCode
    , Line
    , LinkRelationship
    , LoanType
    , Location
    , LodgingUnitDescription
    , LodgingUnitType
    , Longitude
    , LowPrice
    , Material
    , MaterialExtent
    , MathExpression
    , MealService
    , MeasurementMethod
    , MeasurementTechnique
    , MechanismOfAction
    , MeetsEmissionStandard
    , MembershipNumber
    , MemoryRequirements
    , Menu
    , MobileUrl
    , Model
    , MolecularFormula
    , MolecularWeight
    , MonoisotopicMolecularWeight
    , Mpn
    , MuscleAction
    , MusicCompositionForm
    , MusicalKey
    , Naics
    , Name
    , NamedPosition
    , NaturalProgression
    , NegativeNotes
    , NonProprietaryName
    , NormalRange
    , Nsn
    , NumberOfAirbags
    , ObservationPeriod
    , OccupationalCategory
    , OccupationalCredentialAwarded
    , OpeningHours
    , OperatingSystem
    , Option
    , OrderItemNumber
    , OrderNumber
    , OriginalMediaContextDescription
    , Overdosage
    , OwnershipFundingInfo
    , PageEnd
    , PageStart
    , Pagination
    , ParentTaxon
    , PassengerPriorityStatus
    , PassengerSequenceNumber
    , Pathophysiology
    , Pattern
    , PaymentAccepted
    , PaymentMethod
    , PaymentMethodId
    , PaymentStatus
    , Permissions
    , PermittedUsage
    , PetsAllowed
    , PhoneticText
    , PhysicalRequirement
    , PhysiologicalBenefits
    , PlayerType
    , Polygon
    , Position
    , PositiveNotes
    , PossibleComplication
    , PostOfficeBoxNumber
    , PostOp
    , PostalCode
    , PostalCodeBegin
    , PostalCodeEnd
    , PostalCodePrefix
    , PreOp
    , PregnancyWarning
    , Preparation
    , PrescriptionStatus
    , Price
    , PriceCurrency
    , PriceRange
    , PriceType
    , PrintColumn
    , PrintEdition
    , PrintPage
    , PrintSection
    , Procedure
    , ProcessorRequirements
    , ProductGroupID
    , ProductID
    , ProductSupported
    , ProficiencyLevel
    , ProgramName
    , ProgramPrerequisites
    , ProgramType
    , ProgrammingLanguage
    , ProgrammingModel
    , Pronouns
    , PropertyID
    , ProprietaryName
    , ProviderMobility
    , PublicationType
    , Qualifications
    , Query
    , RatingExplanation
    , RatingValue
    , RecipeCategory
    , RecipeCuisine
    , RecipeIngredient
    , RecipeInstructions
    , RecipeYield
    , RecommendationStrength
    , ReleaseNotes
    , RepeatFrequency
    , ReportNumber
    , RequiredCollateral
    , RequiredGender
    , RequiredQuantity
    , Requirements
    , ReservationId
    , Responsibilities
    , RestPeriods
    , ReturnPolicyCountry
    , ReviewAspect
    , ReviewBody
    , Risks
    , RoleName
    , Runtime
    , RuntimePlatform
    , Rxcui
    , SafetyConsideration
    , SalaryCurrency
    , SampleType
    , ScheduleTimezone
    , SchemaVersion
    , SeasonNumber
    , SeatNumber
    , SeatRow
    , SeatSection
    , SeatingType
    , SecurityClearanceRequirement
    , SecurityScreening
    , SensoryRequirement
    , SerialNumber
    , ServesCuisine
    , ServiceType
    , ServingSize
    , Sha256
    , ShippingLabel
    , Significance
    , Size
    , SizeGroup
    , SizeSystem
    , Skills
    , Sku
    , Slogan
    , Smiles
    , SoftwareRequirements
    , SoftwareVersion
    , SpecialCommitments
    , SpeechToTextMarkup
    , Sport
    , StatType
    , Status
    , Step
    , Steps
    , StorageRequirements
    , StreetAddress
    , StrengthUnit
    , StructuralClass
    , SubStageSuffix
    , SubtitleLanguage
    , SuggestedGender
    , Supply
    , Surface
    , TargetDescription
    , TargetName
    , TargetPlatform
    , TargetPopulation
    , TaxID
    , TaxonRank
    , TaxonomicRange
    , Teaches
    , Telephone
    , Temporal
    , TemporalCoverage
    , TermCode
    , TermsOfService
    , games.studiohummingbird.skhema.properties.Text
    , TextValue
    , TickerSymbol
    , TicketNumber
    , TicketToken
    , TimeOfDay
    , TissueSample
    , Title
    , TitleEIDR
    , Tool
    , TotalPrice
    , TouristType
    , TrackingNumber
    , TrainName
    , TrainNumber
    , Transcript
    , TransmitTimeLabel
    , TransmissionMethod
    , TypeOfBed
    , TypicalAgeRange
    , UnitCode
    , UnitText
    , UrlTemplate
    , UsNPI
    , UsesHealthPlanIdStandard
    , Utterances
    , Value
    , ValueName
    , ValuePattern
    , ValueReference
    , VariableMeasured
    , VariablesMeasured
    , VariantCover
    , VariesBy
    , VatID
    , VehicleConfiguration
    , VehicleIdentificationNumber
    , VehicleInteriorColor
    , VehicleInteriorType
    , VehicleSpecialUsage
    , VehicleTransmission
    , Version
    , VideoFormat
    , VideoFrameSize
    , VideoQuality
    , VolumeNumber
    , Warning
    , WorkHours
    , WorstRating
    , Yield
